let banco = []
  banco.push({pt:"sv",en:12})
  banco.push({pt:"pic", en:10})
  banco.push({pt:"pic,sv", en:12 + 10})
  banco.push({pt:"2Pic", en:20})
  banco.push({pt:"3pic", en:30})
  banco.push({pt:"4pic", en:40})
  banco.push({pt:"2sv", en:24})  
  banco.push({pt:"3sv", en:38})
  banco.push({pt:"4sv", en:50})
  banco.push({pt:"2sv,pic", en:25 + 10})
  banco.push({pt:"2pic,sv", en:12 + 20})  
  banco.push({pt:"2pic,2sv", en:20 + 24})
  banco.push({pt:"2sv,2pic", en:20 + 24})
  banco.push({pt:"3sv,3pic", en:38 + 30})
  banco.push({pt:"3pic,3sv", en:38 + 30})  
  banco.push({pt:"4pic,4sv ", en:})
  banco.push({pt:"4sv,4pic", en:})
  banco.push({pt:"3pic,sv", en:})
  banco.push({pt:"3sv,pic", en:})
  banco.push({pt:"5sv", en:})
  banco.push({pt:"", en:})
  banco.push({pt:"", en:})
  banco.push({pt:"", en:})